name: Create Linear Issue Test Workflow

on:
  workflow_dispatch:
    inputs:
      team-id:
        required: true
        type: choice
        description: "Linear Team ID to create the issue for"
        options:
          - CHR
      title:
        required: true
        description: "Title for the Linear Issue"
      description:
        required: true
        description: "Description for the Linear Issue"
      attachment-url:
        description: "URL to attach to the created Linear Issue"
      attachment-title:
        description: "URL Title to attach to the created Linear Issue"

jobs:
  create-linear-issue-job:
    runs-on: ubuntu-latest
    name: A test job
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout action repo
        uses: actions/checkout@v3
      - name: Create the Linear Issue
        id: createIssue
        uses: ./ # Uses an action in the root directory
        with:
          linear-api-key: ${{secrets.LINEAR_API_KEY}}
          linear-team-key: ${{ github.event.inputs.team-id }}
          linear-issue-title: ${{ github.event.inputs.title }}
          linear-issue-description: ${{ github.event.inputs.description }}
          linear-issue-state-id: "d8dc0111-0862-4ea9-8eb5-e7c127f847ce" # Done
          linear-attachment-url: ${{ github.event.inputs.attachment-url }}
          linear-attachment-title: ${{ github.event.inputs.attachment-title }}
      # Use the output from the `hello` step
      - name: Check the outputs
        run: |
          echo "Issue ID: ${{ steps.createIssue.outputs.linear-issue-id }}"
          echo "Issue Identifier: ${{ steps.createIssue.outputs.linear-issue-identifier }}"
          echo "Issue Title: ${{ steps.createIssue.outputs.linear-issue-title }}"
          echo "Issue URL: ${{ steps.createIssue.outputs.linear-issue-url }}"
          echo "Team ID: ${{ steps.createIssue.outputs.linear-team-id }}"
          echo "Team Key: ${{ steps.createIssue.outputs.linear-team-key }}"
          echo "Attachment ID: ${{ steps.createIssue.outputs.linear-attachment-id }}"
